#!/bin/sh
#
# Copyright (C) 1999-2001 Open Source Telecom Corporation.
#  
# This file is free software; as a special exception the author gives
# unlimited permission to copy and/or distribute it, with or without 
# modifications, as long as this notice is preserved.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

if test -x /usr/bin/glibtoolize ; then
        glibtoolize --copy --force
else
        libtoolize --copy --force
fi

ACLOCALDIRS="-I m4"
if [ -d ~/share/aclocal ] ; then
    ACLOCALDIRS="$ACLOCALDIRS -I ~/share/aclocal"
elif [ -d /usr/local/share/aclocal ] ; then
    ACLOCALDIRS="$ACLOCALDIRS -I /usr/local/share/aclocal"
fi

if test ! -z "$1" ; then
	ver=$1
else
	ver="2.53"
fi
aclocal $ACLOCALDIRS
if test -f /usr/bin/autoheader-$ver ; then
	/usr/bin/autoheader-$ver
else
	autoheader
fi
automake --add-missing --copy
if test -f /usr/bin/autoconf-$ver ; then
	/usr/bin/autoconf-$ver
else
	autoconf
fi
rm -f config.cache
