macro(enable_arg _enable_name _enable_default)

if(NOT DEFINED enable-${_enable_name} AND NOT DEFINED disable-${_enable_name})
  set(enable_${_enable_name} ${_enable_default})
elseif(DEFINED enable-${_enable_name})
  if(enable-${_enable_name})
    set(enable_${_enable_name} true)
  else()
    set(enable_${_enable_name} false)
  endif()
  unset(enable-${_enable_name})
  unset(enable-${_enable_name} CACHE)
elseif(DEFINED disable-${_enable_name})
  if(disable-${_enable_name})
    set(enable_${_enable_name} false)
  else()
    set(enable_${_enable_name} true)
  endif()
  unset(disable-${_enable_name})
  unset(disable-${_enable_name} CACHE)
endif()
endmacro()